### ISSUE TITLE
To-Do App Mobile UI (CSS Project-2)

### ISSUE THREAD

**Issue by OxfordMJ007** [OxfordMJ007/To-Do-App-Web#1]
Change the To-Do Web App UI to Mobile UI using  **@media** query.

- [ ] Margin is to be avoided
- [ ] Only use flex or grid
- [ ] Already late with red notice
